version: '3.1'
services:
    tesburys_db:
        image: mysql:5.7
        restart: always
        ports:
            - "23062:3306"
        volumes:
            - "db_data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "tesburys"
            MYSQL_USER: "dockeruser"
            MYSQL_PASSWORD: "dockerpass"
volumes:
    db_data: