spring:
  datasource:
    url: jdbc:mysql://localhost/tesburys?useSSL=false
    username: dockeruser
    password: dockerpass

  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update

server:
  port: 8093